apiVersion: federation-ai.open-cluster-management.io.open-cluster-management.io
kind: FederatedLearning
metadata:
  name: federated-learning-sample
spec:
  framework: flower
  server:
    image: "server-image:latest"
    rounds: 10
    listeners:
      - name: server-listener
        port: 8080
        type: nodePort
  client:
    image: "client-image:latest"
    placement:
      name: federated-learning-client-placement
      namespace: open-cluster-management
