apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: federated-learning-client-placement
  namespace: open-cluster-management
spec:
  clusterSets:
    - global
  predicates:
    - requiredClusterSelector:
        claimSelector:
          matchExpressions:
            - key: federated-learning-sample/client-data
              operator: Exist